---
# tasks file for docker_ubuntu
- name: Install aptitude for Ubuntu
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install docker dependencies for Ubuntu
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - python-setuptools

- name: Add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository for docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker-ce for Ubuntu
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Install docker (using pip package)
  shell: sudo pip install docker

