---
# tasks file for docker_centos
- name: Install Docker dependencies fo CentOS
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python3
      - python3-pip
    state: latest

- name: Add a repository for docker
  copy:
    src: docker-ce.repo
    dest: "/etc/yum.repos.d/docker-ce.repo"
    mode: '0755'

- name: Install docker-ce for CentOS
  yum:
    name: docker-ce
    state: present
    update_cache: yes

- name: Install docker (using pip package installer)
  pip:
    name: docker
    state: present

